### ISSUE TITLE
JWT_SECRET shows error

### ISSUE THREAD

**Issue by shivashishratnam** [sourikghosh/nginx-lua#1]
How to get JWT_SECRET key in order to validate against JWT_TOKEN. I see in code its asking for value in docker run. Does that mean I should give any random values ? 
If not, then suggest something I should do to verify against JWT_TOKEN through this code. Currently the signature is getting verified on jwt.io by using JWKS key in JSON format but how to use here to validate ?

I tried to run docker-run command with custom Secret Key & end up in this issue. 

<img width="1319" alt="Screenshot 2022-04-08 at 9 38 45 AM" src="https://user-images.githubusercontent.com/86949528/162360731-d3685ab4-5f5d-4d4f-a7c6-1a083134094b.png">

**Comment by shivashishratnam** [comment]
@sourikghosh

**Comment by sourikghosh** [comment]
Thanks, @shivashishratnam for pointing this out. ✨

I have updated the documentation with correct syntax
`docker run -e JWT_SECRET="your_jwt_secret" nginx-img`

**Comment by shivashishratnam** [comment]
@sourikghosh Can you shed some light on creating JWT_SECRET to validate against JWT_TOKEN ?
I am unable to do `local jwt_obj = jwt:verify(JWT_SECRET, token,` m it gives me verified as false .

I have actual JWT token in place. But where to retrieve JWT_SECRET from ?

**Comment by shivashishratnam** [comment]
This happens when pubKey is not hardcoded in a proper format.
It would work when


local pubKey = [[-----BEGIN PUBLIC KEY
<contents>
--------END PUBLIC KEY ]]

Moreover the best approach would be to read it from file & compare with JWT Token,
